---
abstract: 'implementation of www.cryptsy.com API'
author:
  - 'Zoffix Znet <cpan@zoffix.com>'
build_requires:
  Data::Dumper: 0
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::Deep: 0
  Test::More: 0
  perl: 5.006
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Cryptsy
provides:
  WebService::Cryptsy:
    file: lib/WebService/Cryptsy.pm
    version: 1.008005
requires:
  Digest::SHA: 0
  HTTP::Request::Common: 0
  JSON::MaybeXS: 0
  LWP::Protocol::https: 0
  LWP::UserAgent: 0
  Moo: 1.004002
  URI: 0
  constant: 0
  overload: 0
  perl: 5.006
resources:
  bugtracker: https://github.com/zoffixznet/webservice-cryptsy/issues
  homepage: http://metacpan.org/release/WebService-Cryptsy
  repository: git://github.com/zoffixznet/webservice-cryptsy.git
version: 1.008005
x_Dist_Zilla:
  perl:
    version: 5.014002
  plugins:
    -
      class: Dist::Zilla::Plugin::OurPkgVersion
      name: '@Author::ZOFFIX/OurPkgVersion'
      version: 0.005001
    -
      class: Dist::Zilla::Plugin::Pod::Spiffy
      name: '@Author::ZOFFIX/Pod::Spiffy'
      version: 1.001007
    -
      class: Dist::Zilla::Plugin::PromptIfStale
      config:
        Dist::Zilla::Plugin::PromptIfStale:
          check_all_plugins: 1
          check_all_prereqs: 1
          modules: []
          phase: release
          skip:
            - strict
            - warnings
            - base
            - ExtUtils::MakeMaker
            - IPC::Open3
            - File::Copy
      name: '@Author::ZOFFIX/PromptIfStale'
      version: 0.027
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Author::ZOFFIX/GatherDir'
      version: 5.020
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Author::ZOFFIX/PruneCruft'
      version: 5.020
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::ZOFFIX/ManifestSkip'
      version: 5.020
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::ZOFFIX/MetaYAML'
      version: 5.020
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::ZOFFIX/License'
      version: 5.020
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Author::ZOFFIX/Readme'
      version: 5.020
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Author::ZOFFIX/ExecDir'
      version: 5.020
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Author::ZOFFIX/ShareDir'
      version: 5.020
    -
      class: Dist::Zilla::Plugin::MakeMaker
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: '@Author::ZOFFIX/MakeMaker'
      version: 5.020
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::ZOFFIX/Manifest'
      version: 5.020
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Author::ZOFFIX/AutoPrereqs'
      version: 5.020
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::ZOFFIX/MetaConfig'
      version: 5.020
    -
      class: Dist::Zilla::Plugin::Prereqs::AuthorDeps
      name: '@Author::ZOFFIX/Prereqs::AuthorDeps'
      version: 0.003
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@Author::ZOFFIX/MinimumPerl'
      version: 1.003
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder_objects:
            -
              class: Dist::Zilla::Plugin::FinderCode
              name: '@Author::ZOFFIX/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
              version: 5.020
        Dist::Zilla::Role::MetaProvider::Provider:
          inherit_missing: 1
          inherit_version: 1
          meta_noindex: 1
      name: '@Author::ZOFFIX/MetaProvides::Package'
      version: 2.001002
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@Author::ZOFFIX/GithubMeta'
      version: 0.46
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: '@Author::ZOFFIX/InstallGuide'
      version: 1.200003
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::ZOFFIX/ReadmeAnyFromPod'
      version: 0.142470
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          bail_out_on_fail: 0
          fail_on_warning: author
          fake_home: 0
          filename: t/00-compile.t
          module_finder:
            - ':InstallModules'
          needs_display: 0
          phase: test
          script_finder:
            - ':ExecFiles'
          skips: []
      name: '@Author::ZOFFIX/Test::Compile'
      version: 2.046
    -
      class: Dist::Zilla::Plugin::Test::DistManifest
      name: '@Author::ZOFFIX/Test::DistManifest'
      version: 2.000004
    -
      class: Dist::Zilla::Plugin::Test::EOL
      name: '@Author::ZOFFIX/Test::EOL'
      version: 0.12
    -
      class: Dist::Zilla::Plugin::Test::Version
      name: '@Author::ZOFFIX/Test::Version'
      version: 0.002004
    -
      class: Dist::Zilla::Plugin::Test::Kwalitee
      config:
        Dist::Zilla::Plugin::Test::Kwalitee:
          filename: xt/release/kwalitee.t
          skiptest: []
      name: '@Author::ZOFFIX/Test::Kwalitee'
      version: 2.11
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@Author::ZOFFIX/MetaTests'
      version: 5.020
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Meta::JSON
      name: '@Author::ZOFFIX/Test::CPAN::Meta::JSON'
      version: 0.003
    -
      class: Dist::Zilla::Plugin::MojibakeTests
      name: '@Author::ZOFFIX/MojibakeTests'
      version: 0.7
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      config:
        Dist::Zilla::Plugin::Test::NoTabs:
          filename: xt/release/no-tabs.t
          finder:
            - ':InstallModules'
            - ':ExecFiles'
            - ':TestFiles'
      name: '@Author::ZOFFIX/NoTabsTests'
      version: 0.09
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Author::ZOFFIX/PodCoverageTests'
      version: 5.020
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::ZOFFIX/PodSyntaxTests'
      version: 5.020
    -
      class: Dist::Zilla::Plugin::Test::Portability
      name: '@Author::ZOFFIX/Test::Portability'
      version: 2.000005
    -
      class: Dist::Zilla::Plugin::Test::Synopsis
      name: '@Author::ZOFFIX/Test::Synopsis'
      version: 2.000005
    -
      class: Dist::Zilla::Plugin::Test::UnusedVars
      name: '@Author::ZOFFIX/Test::UnusedVars'
      version: 2.000006
    -
      class: Dist::Zilla::Plugin::Test::Pod::LinkCheck
      name: '@Author::ZOFFIX/Test::Pod::LinkCheck'
      version: 1.001
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Changes
      name: '@Author::ZOFFIX/Test::CPAN::Changes'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::Test::PodSpelling
      name: '@Author::ZOFFIX/Test::PodSpelling'
      version: 2.006008
    -
      class: Dist::Zilla::Plugin::CheckSelfDependency
      config:
        Dist::Zilla::Plugin::CheckSelfDependency:
          finder:
            - ':InstallModules'
      name: '@Author::ZOFFIX/CheckSelfDependency'
      version: 0.007
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@Author::ZOFFIX/CheckPrereqsIndexed'
      version: 0.012
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: '@Author::ZOFFIX/Test::MinimumVersion'
      version: 2.000005
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      config:
        Dist::Zilla::Plugin::Git::NextVersion:
          first_version: 1.001001
          version_by_branch: 0
          version_regexp: '(?^:^v(.+)$)'
        Dist::Zilla::Role::Git::Repo:
          repo_root: '.'
      name: '@Author::ZOFFIX/Git::NextVersion'
      version: 2.024
    -
      class: Dist::Zilla::Plugin::AutoMetaResources
      name: '@Author::ZOFFIX/AutoMetaResources'
      version: 1.20
    -
      class: Dist::Zilla::Plugin::CopyFilesFromRelease
      name: '@Author::ZOFFIX/CopyFilesFromRelease'
      version: 0.002
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::ZOFFIX/TestRelease'
      version: 5.020
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: '@Author::ZOFFIX/InstallRelease'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::ZOFFIX/ConfirmRelease'
      version: 5.020
    -
      class: Dist::Zilla::Plugin::Git::Check
      config:
        Dist::Zilla::Plugin::Git::Check:
          untracked_files: die
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - dist.ini
            - Changes
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: '.'
      name: '@Author::ZOFFIX/Git::Check'
      version: 2.024
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: v%v%n%n%c
          time_zone: local
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - dist.ini
            - Changes
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: '.'
      name: '@Author::ZOFFIX/Git::Commit'
      version: 2.024
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: ~
          signed: 0
          tag: v1.008005
          tag_format: v%v
          tag_message: v%v
          time_zone: local
        Dist::Zilla::Role::Git::Repo:
          repo_root: '.'
      name: '@Author::ZOFFIX/Git::Tag'
      version: 2.024
    -
      class: Dist::Zilla::Plugin::Git::Push
      config:
        Dist::Zilla::Plugin::Git::Push:
          push_to:
            - origin
          remotes_must_exist: 1
        Dist::Zilla::Role::Git::Repo:
          repo_root: '.'
      name: '@Author::ZOFFIX/Git::Push'
      version: 2.024
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::ZOFFIX/UploadToCPAN'
      version: 5.020
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 5.020
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 5.020
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 5.020
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 5.020
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 5.020
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 5.020
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 5.020
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: 5.020
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: 5.020
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@Author::ZOFFIX/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
      version: 5.020
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 5.020
